### ISSUE TITLE
Added Google API Key and then....

### ISSUE THREAD

**Issue by Sunspoticus** [DNN-Connect/Map#3]
![image](https://user-images.githubusercontent.com/16306427/48519486-53fa8e80-e82a-11e8-836e-fd48c53bb2d8.png)

I have SSL enabled on that page and have authorized the URL in the google api console. Any ideas?

**Comment by Sunspoticus** [comment]
Additional, According to Chrome, Google is complaining about the API key. Looks good to me, but I went and regenerated a new key.. So far nothing.

**Comment by Timo-Breumelhof** [comment]
I don't think this module has been adapted to the obligation to include the api key by google.
(not sure I use pen Content for google maps)
You can check by looking if you see the api key in the page source.

**Comment by Sunspoticus** [comment]
According to the network inspector in Chrome, the module isn't passing my API key..

![image](https://user-images.githubusercontent.com/16306427/48558262-281cee80-e8a6-11e8-846a-ba977a16b941.png)

And then the error Google is returning...

![image](https://user-images.githubusercontent.com/16306427/48558332-4be03480-e8a6-11e8-8fac-ca01d9fba848.png)

**Comment by donker** [comment]
Just fixed this in 01.00.07
